version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: blog-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data
    env_file:
      - ".env"
    networks:
      - blog-api
volumes:
  blog_data:
networks:
  blog-api:
    name: blog-api
    driver: bridge